import Image1 from "./Images/MacBookPro14_Silver.png";
import Image1_1 from "./Images/MacbookPro14_SpaceGray.png";
import Image2 from "./Images/MacBookAirM2_Silver.png";
import Image2_1 from "./Images/MacbookAirM2_Midnight.png"; 

export const Categories = [
  "Laptops",
  "Phones",
  "Tablets",
  "TVs",
  "Accessories",
];

export const mockData = [
  // Laptops
  {
    id: 1,
    images: {Image1, Image1_1},
    name: "MacBook Pro 14-inch",
    price: 1999.99,
    category: "Laptops",
    brand: "Apple",
    screenSize: "14″",
    ram: "16 GB",
    processor: "Apple M2 Pro",
    colors: ["Space Gray", "Silver"],
  },
  {
    id: 2,
    images: {Image2, Image2_1},
    name: "MacBook Air M2",
    price: 1299.99,
    category: "Laptops",
    brand: "Apple",
    screenSize: "13.6″",
    ram: "8 GB",
    processor: "Apple M2",
    colors: ["Silver", "Midnight"],
  },
  {
    id: 3,
    image: Image3,
    name: "XPS 13",
    price: 1199.99,
    category: "Laptops",
    brand: "Dell",
    screenSize: "13.4″",
    ram: "8 GB",
    processor: "Intel Core i5-1240P",
    colors: ["Silver", "Black"],
  },
  {
    id: 4,
    image: Image4,
    name: "XPS 15",
    price: 1599.99,
    category: "Laptops",
    brand: "Dell",
    screenSize: "15.6″",
    ram: "16 GB",
    processor: "Intel Core i7-12700H",
    colors: ["Silver", "Black"],
  },
  {
    id: 5,
    image: Image5,
    name: "ThinkPad X1 Carbon Gen 11",
    price: 1599.99,
    category: "Laptops",
    brand: "Lenovo",
    screenSize: "14″",
    ram: "16 GB",
    processor: "Intel Core i7-1360P",
    colors: ["Black"],
  },
  {
    id: 6,
    image: Image6,
    name: "Yoga Slim 7i",
    price: 999.99,
    category: "Laptops",
    brand: "Lenovo",
    screenSize: "14″",
    ram: "8 GB",
    processor: "Intel Core i5-1235U",
    colors: ["Mineral Grey"],
  },
  {
    id: 7,
    image: Image7,
    name: "Spectre x360 14",
    price: 1399.99,
    category: "Laptops",
    brand: "HP",
    screenSize: "13.5″",
    ram: "16 GB",
    processor: "Intel Core i7-1255U",
    colors: ["Nightfall Black", "Poseidon Blue"],
  },
  {
    id: 8,
    image: Image8,
    name: "ENVY 15",
    price: 1199.99,
    category: "Laptops",
    brand: "HP",
    screenSize: "15.6″",
    ram: "16 GB",
    processor: "AMD Ryzen 7 5800H",
    colors: ["Mica Silver"],
  },
  {
    id: 9,
    image: Image9,
    name: "ZenBook 14",
    price: 1099.99,
    category: "Laptops",
    brand: "Asus",
    screenSize: "14″",
    ram: "16 GB",
    processor: "Intel Core i7-1260P",
    colors: ["Pine Grey", "Lilac Mist"],
  },
  {
    id: 10,
    image: Image10,
    name: "ROG Zephyrus G14",
    price: 1499.99,
    category: "Laptops",
    brand: "Asus",
    screenSize: "14″",
    ram: "16 GB",
    processor: "AMD Ryzen 9 6900HS",
    colors: ["Eclipse Gray"],
  },
  {
    id: 11,
    image: Image1,
    name: "Surface Laptop 5",
    price: 1299.99,
    category: "Laptops",
    brand: "Microsoft",
    screenSize: "13.5″",
    ram: "8 GB",
    processor: "Intel Core i5-1235U",
    colors: ["Platinum", "Matte Black"],
  },
  {
    id: 12,
    image: Image2,
    name: "Swift 3",
    price: 799.99,
    category: "Laptops",
    brand: "Acer",
    screenSize: "14″",
    ram: "8 GB",
    processor: "Intel Core i5-1135G7",
    colors: ["Silver"],
  },

  // Phones
  {
    id: 13,
    image: Image3,
    name: "iPhone 15",
    price: 999.99,
    category: "Phones",
    brand: "Apple",
    screenSize: "6.1″",
    ram: "6 GB",
    storage: "128 GB",
    camera: "48 MP",
    colors: ["Black", "White", "Red"],
  },
  {
    id: 14,
    image: Image4,
    name: "iPhone 15 Pro",
    price: 1199.99,
    category: "Phones",
    brand: "Apple",
    screenSize: "6.1″",
    ram: "8 GB",
    storage: "256 GB",
    camera: "48 MP",
    colors: ["Graphite", "Gold", "Silver", "Blue"],
  },
  {
    id: 15,
    image: Image5,
    name: "Galaxy S24",
    price: 899.99,
    category: "Phones",
    brand: "Samsung",
    screenSize: "6.2″",
    ram: "8 GB",
    storage: "256 GB",
    camera: "50 MP",
    colors: ["Phantom Black", "Cream", "Graphite"],
  },
  {
    id: 16,
    image: Image6,
    name: "Galaxy S24+",
    price: 999.99,
    category: "Phones",
    brand: "Samsung",
    screenSize: "6.7″",
    ram: "8 GB",
    storage: "256 GB",
    camera: "50 MP",
    colors: ["Phantom Black", "Light Violet", "Green"],
  },
  {
    id: 17,
    image: Image7,
    name: "Pixel 8",
    price: 699.99,
    category: "Phones",
    brand: "Google",
    screenSize: "6.2″",
    ram: "8 GB",
    storage: "128 GB",
    camera: "50 MP",
    colors: ["Lemongrass", "Obsidian", "Rose"],
  },
  {
    id: 18,
    image: Image8,
    name: "Pixel 8 Pro",
    price: 999.99,
    category: "Phones",
    brand: "Google",
    screenSize: "6.7″",
    ram: "12 GB",
    storage: "256 GB",
    camera: "50 MP",
    colors: ["Hazel", "Bay", "Obsidian"],
  },
  {
    id: 19,
    image: Image9,
    name: "OnePlus 11",
    price: 749.99,
    category: "Phones",
    brand: "OnePlus",
    screenSize: "6.7″",
    ram: "8 GB",
    storage: "128 GB",
    camera: "50 MP",
    colors: ["Mirror Black", "Eternal Green"],
  },
  {
    id: 20,
    image: Image10,
    name: "OnePlus 11 Pro",
    price: 799.99,
    category: "Phones",
    brand: "OnePlus",
    screenSize: "6.7″",
    ram: "12 GB",
    storage: "256 GB",
    camera: "50 MP",
    colors: ["Dawn Light", "Volcanic Black"],
  },
  {
    id: 21,
    image: Image1,
    name: "Xiaomi 13",
    price: 799.99,
    category: "Phones",
    brand: "Xiaomi",
    screenSize: "6.36″",
    ram: "8 GB",
    storage: "128 GB",
    camera: "50 MP",
    colors: ["Black", "White"],
  },
  {
    id: 22,
    image: Image2,
    name: "Xiaomi 13 Pro",
    price: 849.99,
    category: "Phones",
    brand: "Xiaomi",
    screenSize: "6.73″",
    ram: "12 GB",
    storage: "256 GB",
    camera: "50 MP",
    colors: ["Black", "Blue"],
  },

  // Tablets (new items id 23-30)
  {
    id: 23,
    image: Image3,
    name: "iPad Mini",
    price: 499.99,
    category: "Tablets",
    brand: "Apple",
    screenSize: "8.3″",
    storage: "64 GB",
    connectivity: "Wi-Fi",
    colors: ["Space Gray", "Pink", "Purple"],
  },
  {
    id: 24,
    image: Image4,
    name: "Galaxy Tab S7 FE",
    price: 549.99,
    category: "Tablets",
    brand: "Samsung",
    screenSize: "12.4″",
    storage: "64 GB",
    connectivity: "Wi-Fi + LTE",
    colors: ["Mystic Black", "Mystic Silver"],
  },
  {
    id: 25,
    image: Image5,
    name: "Tab P11",
    price: 329.99,
    category: "Tablets",
    brand: "Lenovo",
    screenSize: "11″",
    storage: "128 GB",
    connectivity: "Wi-Fi",
    colors: ["Slate Grey"],
  },
  {
    id: 26,
    image: Image6,
    name: "Fire HD 8",
    price: 89.99,
    category: "Tablets",
    brand: "Amazon",
    screenSize: "8″",
    storage: "32 GB",
    connectivity: "Wi-Fi",
    colors: ["Black", "Twilight Blue", "Plum"],
  },
  {
    id: 27,
    image: Image7,
    name: "Galaxy Tab A7 Lite",
    price: 159.99,
    category: "Tablets",
    brand: "Samsung",
    screenSize: "8.7″",
    storage: "32 GB",
    connectivity: "Wi-Fi",
    colors: ["Gray", "Silver"],
  },
  {
    id: 28,
    image: Image8,
    name: "Pixel Tablet",
    price: 499.99,
    category: "Tablets",
    brand: "Google",
    screenSize: "10.95″",
    storage: "128 GB",
    connectivity: "Wi-Fi",
    colors: ["Rose", "Porcelain"],
  },
  {
    id: 29,
    image: Image9,
    name: "Tab M10 FHD Plus",
    price: 199.99,
    category: "Tablets",
    brand: "Lenovo",
    screenSize: "10.3″",
    storage: "64 GB",
    connectivity: "Wi-Fi",
    colors: ["Slate Grey"],
  },
  {
    id: 30,
    image: Image10,
    name: "Surface Pro 9",
    price: 999.99,
    category: "Tablets",
    brand: "Microsoft",
    screenSize: "13″",
    storage: "128 GB",
    connectivity: "Wi-Fi + 5G",
    colors: ["Platinum", "Graphite"],
  },

  // TVs (new items id 31-38)
  {
    id: 31,
    image: Image1,
    name: "Samsung Frame 55″",
    price: 1499.99,
    category: "TVs",
    brand: "Samsung",
    screenSize: "55″",
    resolution: "4K UHD",
    smartTv: true,
    colors: ["Beige Frame", "White Frame"],
  },
  {
    id: 32,
    image: Image2,
    name: "LG C2 OLED 42″",
    price: 1299.99,
    category: "TVs",
    brand: "LG",
    screenSize: "42″",
    resolution: "4K UHD",
    smartTv: true,
    colors: ["Black"],
  },
  {
    id: 33,
    image: Image3,
    name: "Sony X80L 50″",
    price: 599.99,
    category: "TVs",
    brand: "Sony",
    screenSize: "50″",
    resolution: "4K UHD",
    smartTv: true,
    colors: ["Black"],
  },
  {
    id: 34,
    image: Image4,
    name: "TCL 65″ Q6 QLED",
    price: 799.99,
    category: "TVs",
    brand: "TCL",
    screenSize: "65″",
    resolution: "4K UHD",
    smartTv: true,
    colors: ["Black"],
  },
  {
    id: 35,
    image: Image5,
    name: "Hisense U6G 55″",
    price: 699.99,
    category: "TVs",
    brand: "Hisense",
    screenSize: "55″",
    resolution: "4K UHD",
    smartTv: true,
    colors: ["Black"],
  },
  {
    id: 36,
    image: Image6,
    name: "Vizio M-Series 65″",
    price: 999.99,
    category: "TVs",
    brand: "Vizio",
    screenSize: "65″",
    resolution: "4K UHD",
    smartTv: true,
    colors: ["Black"],
  },
  {
    id: 37,
    image: Image7,
    name: "Philips Ambilight 55″",
    price: 1199.99,
    category: "TVs",
    brand: "Philips",
    screenSize: "55″",
    resolution: "4K UHD",
    smartTv: true,
    colors: ["Black"],
  },
  {
    id: 38,
    image: Image8,
    name: "Panasonic TX-43JX750",
    price: 499.99,
    category: "TVs",
    brand: "Panasonic",
    screenSize: "43″",
    resolution: "4K HD",
    smartTv: false,
    colors: ["Black"],
  },

  // Accessories (new items id 39-51)
  {
    id: 39,
    image: Image9,
    name: "MagSafe Charger",
    price: 39.99,
    category: "Accessories",
    brand: "Apple",
    batteryLife: null,
    compatibility: "iPhone 12+",
    colors: ["White"],
  },
  {
    id: 40,
    image: Image10,
    name: "Wireless Charger Duo",
    price: 79.99,
    category: "Accessories",
    brand: "Samsung",
    batteryLife: null,
    compatibility: "Qi devices",
    colors: ["Black", "White"],
  },
  {
    id: 41,
    image: Image1,
    name: "MX Master 3 Mouse",
    price: 99.99,
    category: "Accessories",
    brand: "Logitech",
    batteryLife: "70 days",
    colors: ["Graphite", "Midnight Teal"],
  },
  {
    id: 42,
    image: Image2,
    name: "K380 Bluetooth Keyboard",
    price: 39.99,
    category: "Accessories",
    brand: "Logitech",
    batteryLife: "2 years",
    colors: ["Off-white", "Rose", "Graphite"],
  },
  {
    id: 43,
    image: Image3,
    name: "PowerLine+ USB-C Cable",
    price: 19.99,
    category: "Accessories",
    brand: "Anker",
    length: "3 ft",
    colors: ["Red", "Black"],
  },
  {
    id: 44,
    image: Image4,
    name: "SanDisk Extreme 128GB SD Card",
    price: 24.99,
    category: "Accessories",
    brand: "SanDisk",
    readSpeed: "150MB/s",
    colors: ["Red & Black"],
  },
  {
    id: 45,
    image: Image5,
    name: "Surge Protector 6-Outlet",
    price: 29.99,
    category: "Accessories",
    brand: "Belkin",
    maxLoad: "1875W",
    colors: ["Black"],
  },
  {
    id: 46,
    image: Image6,
    name: "C920 HD Webcam",
    price: 69.99,
    category: "Accessories",
    brand: "Logitech",
    resolution: "1080p",
    colors: ["Black"],
  },
  {
    id: 47,
    image: Image7,
    name: "Yeti USB Microphone",
    price: 129.99,
    category: "Accessories",
    brand: "Blue",
    polarPattern: "Cardioid",
    colors: ["Silver", "Blackout"],
  },
  {
    id: 48,
    image: Image8,
    name: "DeathAdder V2 Mouse",
    price: 49.99,
    category: "Accessories",
    brand: "Razer",
    connection: "Wired",
    colors: ["Black"],
  },
  {
    id: 49,
    image: Image9,
    name: "K95 RGB Keyboard",
    price: 199.99,
    category: "Accessories",
    brand: "Corsair",
    switchType: "Cherry MX Red",
    colors: ["Black"],
  },
  {
    id: 50,
    image: Image10,
    name: "WH-CH710N Headphones",
    price: 149.99,
    category: "Accessories",
    brand: "Sony",
    batteryLife: "35 hrs",
    colors: ["Blue", "Black"],
  },
  {
    id: 51,
    image: Image1,
    name: "SoundLink II Speaker",
    price: 179.99,
    category: "Accessories",
    brand: "Bose",
    batteryLife: "8 hrs",
    colors: ["Black"],
  },
];